BEGIN

CREATE TABLE USER
   (ID INTEGER AUTOINCREMENT PRIMARY KEY,
    NAME           TEXT    NOT NULL,
    AGE            INT     NOT NULL,
    ADDRESS        TEXT,
    SALARY         REAL);

INSERT INTO USER (NAME,AGE,ADDRESS,SALARY)
    VALUES ('Paul', 32, 'California', 20000.00);

INSERT INTO USER (NAME,AGE,ADDRESS,SALARY)
    VALUES ('Paul', 32, 'California', 20000.00);

INSERT INTO USER (NAME,AGE,ADDRESS,SALARY)
    VALUES ('Paul', 32, 'California', 20000.00);

COMMIT